name: Build Artifact

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Windows Artifact
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: fluxent
        submodules: true

    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/xent-core
        path: xent-core

    - uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@master

    - name: Configure
      working-directory: fluxent
      run: xmake f -m release -a x64 -y

    - name: Build
      working-directory: fluxent
      run: xmake

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hello_fluxent
        path: fluxent/build/windows/x64/release/hello_fluxent.exe
